package conf

import "github.com/p9c/pod/cmd/gui/vue/mod"

func GetPanels() map[string]mod.EJSlayout {
	return map[string]mod.EJSlayout{
		"overview": {
			AllowDragging:     false,
			AllowFloating:     false,
			AllowResizing:     false,
			CellSpacing:       []int{15, 15},
			CellAspectRatio:   "100/69",
			Columns:           9,
			EnablePersistence: true,
			EnableRtl:         false,
			Panels: []mod.EJSpanel{
				{
					SizeX:    2,
					SizeY:    2,
					MinSizeX: 2,
					MinSizeY: 1,
					MaxSizeX: 3,
					MaxSizeY: 1,
					Col:      0,
					Row:      9,
					ZIndex:   0,
					ID:       "panelstatus",
					Header:   "<div class='e-header-text'>Status</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelstatus' id='panelstatus' class='panel-content'></div>",
				},
				{
					SizeX:    4,
					SizeY:    2,
					MinSizeX: 4,
					MinSizeY: 2,
					MaxSizeX: 4,
					MaxSizeY: 2,
					Col:      0,
					Row:      0,
					ZIndex:   0,
					ID:       "panelwalletstatus",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelwalletstatus' id='panelwalletstatus' class='panel-content'></div>",
				},
				{
					SizeX:    5,
					SizeY:    2,
					MinSizeX: 3,
					MinSizeY: 2,
					MaxSizeX: 5,
					MaxSizeY: 2,
					Col:      4,
					Row:      0,
					ZIndex:   0,
					ID:       "panelsend",
					CssClass: "noPanelFrame",
					Enabled:  true,
					Content:  "<div is='panelsend' id='panelsend' class='panel-content'></div>",
				},
				//{
				//	SizeX:    3,
				//	SizeY:    3,
				//	MinSizeX: 3,
				//	MinSizeY: 2,
				//	MaxSizeX: 9,
				//	MaxSizeY: 5,
				//	Col:      8,
				//	Row:      3,
				//	ZIndex:   0,
				//	ID:       "paneltest",
				//	Header:   <div class='e-header-text'>"Test</div><div class='header-border'></div>",
				//	CssClass: "panel",
				//	Enabled:  true,
				//	Content:  "<div is='paneltest' id='paneltest' class='panel-content'></div>test",
				//},
				//{
				//	SizeX:    6,
				//	SizeY:    3,
				//	MinSizeX: 5,
				//	MinSizeY: 2,
				//	MaxSizeX: 9,
				//	MaxSizeY: 5,
				//	Col:      0,
				//	Row:      2,
				//	ZIndex:   0,
				//	ID:       "panelpeers",
				//	Header:   "<div class='e-header-text'>Peers</div><div class='header-border'></div>",
				//	CssClass: "panel",
				//	Enabled:  true,
				//	Content:  "<div is='panelpeers' id='panelpeers' class='panel-content'></div>",
				//},
				{
					SizeX:    6,
					SizeY:    4,
					MinSizeX: 6,
					MinSizeY: 4,
					MaxSizeX: 6,
					MaxSizeY: 4,
					Col:      0,
					Row:      2,
					ZIndex:   0,
					ID:       "paneltxsex",
					Header:   "<div class='e-header-text'>Transactions</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='paneltxsex' id='paneltxsex' class='panel-content'></div>",
				},
				{
					SizeX:    6,
					SizeY:    4,
					MinSizeX: 6,
					MinSizeY: 4,
					MaxSizeX: 6,
					MaxSizeY: 4,
					Col:      0,
					Row:      6,
					ZIndex:   0,
					ID:       "paneltimebalance",
					Header:   "<div class='e-header-text'>Balance</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='paneltimebalance' id='paneltimebalance' class='panel-content'></div>",
				},
				{
					SizeX:    2,
					SizeY:    2,
					MinSizeX: 2,
					MinSizeY: 2,
					MaxSizeX: 2,
					MaxSizeY: 2,
					Col:      7,
					Row:      2,
					ZIndex:   0,
					ID:       "panellocalhashrate",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panellocalhashrate' id='panellocalhashrate' class='panel-content'></div>",
				},
				{
					SizeX:    2,
					SizeY:    2,
					MinSizeX: 2,
					MinSizeY: 2,
					MaxSizeX: 2,
					MaxSizeY: 2,
					Col:      7,
					Row:      4,
					ZIndex:   0,
					ID:       "panelnetworkhashrate",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelnetworkhashrate' id='panelnetworkhashrate' class='panel-content'></div>",
				},
			},
		},
		"settings": {
			AllowDragging:     false,
			AllowFloating:     true,
			AllowResizing:     false,
			CellAspectRatio:   "145/100",
			Columns:           3,
			EnablePersistence: true,
			EnableRtl:         false,
			Panels: []mod.EJSpanel{
				{
					SizeX:    2,
					SizeY:    1,
					MinSizeX: 2,
					MinSizeY: 1,
					MaxSizeX: 3,
					MaxSizeY: 3,
					Col:      0,
					Row:      0,
					ZIndex:   0,
					ID:       "paneldaemonconf",
					Header:   "<div class='e-header-text'>Daemon configuration</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='paneldaemonconf' id='paneldaemonconf' class='panel-content'></div>",
				},
				{
					SizeX:    1,
					SizeY:    1,
					MinSizeX: 1,
					MinSizeY: 1,
					MaxSizeX: 1,
					MaxSizeY: 1,
					Col:      2,
					Row:      0,
					ZIndex:   0,
					ID:       "panelmanager",
					Header:   "<div class='e-header-text'>Manager</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelmanager' id='panelmanager' class='panel-content'></div>",
				},
			},
			//},
		},
		//"blockexplorer": {
		//	Columns:           9,
		//	EnablePersistence: true,
		//	Panels: []mod.EJSpanel{
		//		{
		//			SizeX:    4,
		//			SizeY:    2,
		//			MinSizeX: 3,
		//			MinSizeY: 2,
		//			MaxSizeX: 9,
		//			MaxSizeY: 5,
		//			Col:      0,
		//			Row:      4,
		//			ZIndex:   0,
		//			ID:       "panelblockexplorer",
		//			Header:   "<div class='e-header-text'>Block Explorer</div><div class='header-border'></div>",
		//			CssClass: " ",
		//			Enabled:  false,
		//			Content:  "<div class='panel-content' is='panelblockexplorer' id='panelblockexplorer'></div>",
		//		},
		//	},
		//},
		"transactions": {
			AllowDragging:     false,
			AllowFloating:     true,
			AllowResizing:     false,
			CellAspectRatio:   "145/100",
			Columns:           1,
			EnableRtl:         false,
			EnablePersistence: true,
			Panels: []mod.EJSpanel{
				{
					SizeX:    1,
					SizeY:    1,
					MinSizeX: 1,
					MinSizeY: 1,
					MaxSizeX: 1,
					MaxSizeY: 1,
					Col:      0,
					Row:      0,
					ZIndex:   0,
					ID:       "paneltransactions",
					Header:   "<div class='e-header-text'>Transactions</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div class='panel-content' is='paneltransactions' id='paneltransactions'></div>",
				},
			},
		},
		"addressbook": {
			AllowDragging:     false,
			AllowFloating:     true,
			AllowResizing:     false,
			CellAspectRatio:   "145/100",
			Columns:           1,
			EnableRtl:         false,
			EnablePersistence: true,
			Panels: []mod.EJSpanel{
				{
					SizeX:    1,
					SizeY:    1,
					MinSizeX: 1,
					MinSizeY: 1,
					MaxSizeX: 1,
					MaxSizeY: 1,
					Col:      0,
					Row:      0,
					ZIndex:   0,
					ID:       "paneladdressbook",
					Header:   "<div class='e-header-text'>Address Book</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div class='panel-content' is='paneladdressbook' id='paneladdressbook'></div>",
				},
			},
		},
		"charts": {
			AllowDragging:     false,
			AllowFloating:     true,
			AllowResizing:     false,
			CellAspectRatio:   "145/100",
			Columns:           1,
			EnableRtl:         false,
			EnablePersistence: true,
			Panels: []mod.EJSpanel{
				{
					SizeX:    1,
					SizeY:    1,
					MinSizeX: 1,
					MinSizeY: 1,
					MaxSizeX: 1,
					MaxSizeY: 1,
					Col:      0,
					Row:      0,
					ZIndex:   0,
					ID:       "panelcharta",
					Header:   "<div class='e-header-text'>Chart A</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelcharta' id='panelcharta' class='panel-content'></div>",
				},
				{
					SizeX:    2,
					SizeY:    2,
					MinSizeX: 3,
					MinSizeY: 2,
					MaxSizeX: 9,
					MaxSizeY: 5,
					Col:      5,
					Row:      0,
					ZIndex:   0,
					ID:       "panelchartb",
					Header:   "<div class='e-header-text'>Chart B</div><div class='header-border'></div>",
					CssClass: "panel",
					Enabled:  true,
					Content:  "<div is='panelchartb' id='panelchartb' class='panel-content'></div>",
				},
			},
		},
	}
}
