package conf

import "github.com/p9c/pod/cmd/gui/vue/mod"

var GetParallelCoinRepo = []mod.DuoVUEcomp{
	{
		IsApp:       true,
		Name:        "Core",
		ID:          "core",
		Version:     "0.0.1",
		Description: "Core component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "core",
		SubType:     "core",
	},
	{
		IsApp:       true,
		Name:        "Boot",
		ID:          "boot",
		Version:     "0.0.1",
		Description: "Boot component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "core",
		SubType:     "boot",
	},
	{
		IsApp:       true,
		Name:        "Dev",
		ID:          "dev",
		Version:     "0.0.1",
		Description: "Developer component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "core",
		SubType:     "dev",
	},
	{
		IsApp:       true,
		Name:        "Display",
		ID:          "display",
		Version:     "0.0.1",
		Description: "Display component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "core",
		SubType:     "display",
	},
	{
		IsApp:       true,
		Name:        "Nav",
		ID:          "nav",
		Version:     "0.0.1",
		Description: "Navigation component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "core",
		SubType:     "nav",
	},
	{
		IsApp:       true,
		Name:        "Manager",
		ID:          "manager",
		Version:     "0.0.1",
		Description: "Components manager component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "panel",
		SubType:     "manager",
	},

	{
		IsApp:       true,
		Name:        "Settings",
		ID:          "settings",
		Version:     "0.0.1",
		Description: "Settings component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "panel",
		SubType:     "settings",
	},
	{
		IsApp:       true,
		Name:        "Node",
		ID:          "node",
		Version:     "0.0.1",
		Description: "Node component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "service",
		SubType:     "node",
	},
	{
		IsApp:       true,
		Name:        "Wallet",
		ID:          "wallet",
		Version:     "0.0.1",
		Description: "Wallet component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "panel",
		SubType:     "wallet",
	},
	{
		IsApp:       true,
		Name:        "Transactions",
		ID:          "transactions",
		Version:     "0.0.1",
		Description: "Transactions component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "panel",
		SubType:     "manager",
	},
	{
		IsApp:       true,
		Name:        "Peers",
		ID:          "peers",
		Version:     "0.0.1",
		Description: "Peers component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "panel",
		SubType:     "wallet",
	},
	{
		IsApp:       true,
		Name:        "Console",
		ID:          "console",
		Version:     "0.0.1",
		Description: "Console component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "panel",
		SubType:     "manager",
	},
	{
		IsApp:       true,
		Name:        "Address book",
		ID:          "addressbook",
		Version:     "0.0.1",
		Description: "Address book component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "panel",
		SubType:     "wallet",
	},
	{
		IsApp:       true,
		Name:        "Explorer",
		ID:          "explorer",
		Version:     "0.0.1",
		Description: "Explorer component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "panel",
		SubType:     "manager",
	},
	{
		IsApp:       true,
		Name:        "Status",
		ID:          "status",
		Version:     "0.0.1",
		Description: "Status panel component of ParallelCoin Wallet",
		State:       "active",
		Image:       "img",
		URL:         "url",
		CompType:    "panel",
		SubType:     "status",
	},
}
